### ISSUE TITLE
Cancel button doesn't work.

### ISSUE THREAD

**Issue by pxcasey** [drivardxrm/IconOptionSet.PCF#19]
Cancel would sometimes work, sometimes doesn't on existing records. It never works when creating new records.

**Comment by drivardxrm** [comment]
Hi @pxcasey,
Sorry for the late response, I just saw the comment.

I will have a look at this when I have time.

Thanks for raising the issue

**Comment by drivardxrm** [comment]
Hi @pxcasey,

I finally found some time to work on the control.
This bug should be fixed inthe latest version : https://github.com/drivardxrm/IconOptionSet.PCF/releases/tag/v1.0.6.0

Again thanks for your feedback, tell me if it woks well on your side.

**Comment by drivardxrm** [comment]
Fixed in https://github.com/drivardxrm/IconOptionSet.PCF/releases/tag/v1.0.6.0

**Comment by pxcasey** [comment]
Hi @drivardxrm 
I can verify that this is working now.
